import { Link } from "react-router-dom";

const productLinks = [["Dashboard", "/dashboard"], ["Library", "/library"], ["Notes", "/notes"], ["Quiz", "/quiz"], ["Flashcards", "/flashcards"], ["AI Chat", "/chatbot"], ["Study Planner", "/planner"], ["Analytics", "/analytics"], ["Leaderboard", "/leaderboard"]];
const resourceLinks = [["Study Materials", "/library"], ["Exam Preparation", "/quiz"], ["AI Study Assistant", "/chatbot"], ["Study Planner", "/planner"], ["Learning Analytics", "/analytics"]];

function FooterLinks({ title, links }) {
  return <nav aria-labelledby={`footer-${title.toLowerCase().replaceAll(" ", "-")}`}><h2 id={`footer-${title.toLowerCase().replaceAll(" ", "-")}`} className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">{title}</h2><ul className="mt-4 space-y-2.5">{links.map(([label, to]) => <li key={`${label}-${to}`}><Link to={to} className="text-sm text-zinc-500 transition hover:text-white focus:outline-none focus-visible:text-[#65ff45]">{label}</Link></li>)}</ul></nav>;
}

export default function Footer() {
  return <footer className="border-t border-white/10 bg-[#0b0b0d]" aria-label="StudyGenie AI footer"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-6 lg:grid-cols-[1.35fr_1fr_1fr_1fr] lg:px-8"><div><Link to="/" className="font-[Space_Grotesk] text-xl font-bold text-white">StudyGenie <span className="text-[#65ff45]">AI</span></Link><p className="mt-4 max-w-xs text-sm leading-6 text-zinc-500">Your AI-powered companion for smarter, structured, and exam-ready learning.</p><a href="mailto:studygenie@gmail.com" className="mt-5 inline-block max-w-full break-all text-sm text-[#65ff45] transition hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-[#39ff14]">studygenie@gmail.com</a></div><FooterLinks title="Product" links={productLinks} /><FooterLinks title="Resources" links={resourceLinks} /><nav aria-labelledby="footer-support"><h2 id="footer-support" className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Support</h2><ul className="mt-4 space-y-2.5 text-sm text-zinc-500"><li>Help Center</li><li>FAQ</li><li>Contact</li><li>Feedback</li><li><a href="mailto:studygenie@gmail.com" className="text-[#65ff45] hover:text-white">Email support</a></li></ul></nav></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-6 text-xs text-zinc-600 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><div className="flex flex-wrap gap-x-5 gap-y-2"><span>Privacy Policy</span><span>Terms of Service</span><span>Cookie Policy</span></div><span>© {new Date().getFullYear()} StudyGenie AI. All rights reserved.</span><span className="text-zinc-500">Made for students · Built with AI · Learn smarter</span></div></div></footer>;
}
