import { useContext, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { BarChart3, BookOpen, Bot, Brain, CalendarDays, FileUp, GraduationCap, Layers3, Menu, Settings, Trophy, UserRound, X } from "lucide-react";
import { AuthContext } from "../../context/AuthContext";

const navItems = [
  ["Dashboard", "/dashboard", BarChart3], ["My Library", "/library", BookOpen], ["Upload PDF", "/upload", FileUp], ["AI Tutor", "/chatbot", Bot], ["Notes History", "/notes", Brain], ["Flashcards", "/flashcards", Layers3], ["Quiz Generator", "/quiz", GraduationCap], ["Study Planner", "/planner", CalendarDays], ["Analytics", "/analytics", BarChart3], ["Community", "/leaderboard", Trophy], ["Profile", "/profile", UserRound], ["Settings", "/settings", Settings],
];

export default function Sidebar() {
  const [open, setOpen] = useState(false); const navigate = useNavigate(); const location = useLocation(); const { logout, user } = useContext(AuthContext);
  const go = (to) => { navigate(to); setOpen(false); };
  return <><button onClick={() => setOpen(true)} aria-expanded={open} aria-controls="mobile-navigation" className="fixed left-4 top-4 z-[60] grid h-12 w-12 place-items-center rounded-xl border border-[#39ff14]/35 bg-[#101713] text-[#65ff45] shadow-[0_0_18px_rgba(57,255,20,.14)] transition hover:border-[#39ff14] hover:bg-[#39ff14]/10 lg:hidden" aria-label="Open navigation menu"><Menu size={24} strokeWidth={2.5}/></button><aside id="mobile-navigation" className={`fixed inset-y-0 left-0 z-50 flex w-[min(258px,85vw)] flex-col border-r border-white/10 bg-[#0c1010]/95 px-4 py-5 shadow-2xl backdrop-blur-xl transition-transform duration-300 lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex items-center justify-between"><button onClick={() => go("/dashboard")} className="flex items-center gap-3 text-left"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#39ff14] text-[#071006] shadow-[0_0_24px_rgba(57,255,20,.3)]"><Bot size={23}/></span><span><strong className="block text-base tracking-tight text-white">StudyGenie <i className="not-italic text-[#65ff45]">AI</i></strong><small className="text-[10px] text-[#65ff45]">Your AI Study Companion</small></span></button><button onClick={() => setOpen(false)} className="text-zinc-400 lg:hidden" aria-label="Close menu"><X/></button></div><nav className="mt-8 flex-1 space-y-1 overflow-y-auto">{navItems.map(([label,to,Icon])=>{const active=location.pathname===to;return <button key={`${label}-${to}`} onClick={()=>go(to)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium transition ${active ? "bg-[#39ff14] text-[#071006] shadow-[0_0_24px_rgba(57,255,20,.2)]" : "text-zinc-300 hover:bg-white/5 hover:text-[#65ff45]"}`}><Icon size={18}/><span>{label}</span></button>})}</nav><div className="neon-card rounded-2xl p-4"><p className="text-xs font-semibold text-[#65ff45]">{user?.name || "Study workspace"}</p><p className="mt-1 text-xs leading-5 text-zinc-400">Create focused study resources from your private materials.</p><button onClick={()=>go("/upload")} className="mt-3 w-full rounded-lg bg-[#39ff14] px-3 py-2 text-xs font-bold text-[#071006]">Upload material</button></div><button onClick={()=>{logout();navigate("/login")}} className="mt-3 rounded-xl px-3 py-2 text-left text-sm text-zinc-400 transition hover:bg-white/5 hover:text-white">Sign out</button></aside>{open&&<button aria-label="Close menu overlay" onClick={()=>setOpen(false)} className="fixed inset-0 z-40 bg-black/60 lg:hidden"/>}</>;
}
