import { useContext, useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpen, BrainCircuit, CalendarDays, CheckCircle2, Clock3, FileText, Flame, Layers3, MessageCircle, Plus, Sparkles, Target, Trophy, UploadCloud } from "lucide-react";
import { Link } from "react-router-dom";
import api from "../api/axios";
import { AuthContext } from "../context/AuthContext";

const dayName = (date) => new Date(date).toLocaleDateString(undefined, { weekday: "short" });
const dateLabel = (date) => new Date(date).toLocaleDateString(undefined, { month: "short", day: "numeric" });

function Skeleton({ className = "h-28" }) { return <div className={`animate-pulse rounded-2xl border border-white/10 bg-white/[.04] ${className}`} />; }

function ActionCard({ icon: Icon, title, description, to, accent = "green" }) {
  return <Link to={to} className={`group rounded-2xl border p-5 transition duration-300 hover:-translate-y-1 ${accent === "green" ? "border-[#39ff14]/20 bg-[#39ff14]/[.05] hover:border-[#39ff14]/50 hover:shadow-[0_0_28px_rgba(57,255,20,.1)]" : "border-white/10 bg-white/[.025] hover:border-[#39ff14]/35"}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#39ff14]/10 text-[#65ff45] transition group-hover:bg-[#39ff14]/20"><Icon size={20} /></span><h3 className="mt-5 font-semibold text-white">{title}</h3><p className="mt-1 text-xs leading-5 text-zinc-500">{description}</p></Link>;
}

function StatCard({ icon: Icon, label, value, hint }) {
  return <article className="group rounded-2xl border border-white/10 bg-[#0d1110] p-5 transition hover:-translate-y-0.5 hover:border-[#39ff14]/30"><Icon size={19} className="text-[#65ff45]" /><p className="mt-5 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-sm text-zinc-400">{label}</p>{hint && <p className="mt-3 text-[11px] text-zinc-600">{hint}</p>}</article>;
}

export default function Dashboard() {
  const { user } = useContext(AuthContext);
  const [analytics, setAnalytics] = useState(null);
  const [pdfs, setPdfs] = useState([]);
  const [notes, setNotes] = useState([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    Promise.all([api.get("/user/analytics"), api.get("/pdf"), api.get("/notes")])
      .then(([analyticsResponse, pdfResponse, notesResponse]) => {
        if (!mounted) return;
        setAnalytics(analyticsResponse.data.analytics);
        setPdfs(pdfResponse.data || []);
        setNotes((notesResponse.data.notes || []).filter((note) => note.status === "completed"));
      })
      .catch((requestError) => { if (mounted) setError(requestError.response?.data?.message || "Could not load your workspace."); })
      .finally(() => { if (mounted) setLoading(false); });
    return () => { mounted = false; };
  }, []);

  const weeklyMaterials = useMemo(() => {
    const now = Date.now();
    const days = Array.from({ length: 7 }, (_, index) => {
      const date = new Date(now - ((6 - index) * 24 * 60 * 60 * 1000));
      const key = date.toDateString();
      const pdfCount = pdfs.filter((pdf) => new Date(pdf.createdAt).toDateString() === key).length;
      const noteCount = notes.filter((note) => new Date(note.createdAt).toDateString() === key).length;
      return { label: dayName(date), date, count: pdfCount + noteCount };
    });
    return days;
  }, [notes, pdfs]);

  const recentPdfs = pdfs.slice().sort((a, b) => new Date(b.updatedAt || b.createdAt) - new Date(a.updatedAt || a.createdAt)).slice(0, 4);
  const recentNotes = notes.slice().sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 3);
  const progress = analytics?.flashcardProgress || 0;
  const recommendation = !pdfs.length ? { title: "Start with your first study material", text: "Upload a PDF so Genie can build your private study workspace." } : progress < 50 ? { title: "Build flashcard mastery", text: "You have learned fewer than half of your generated flashcards. A short review session is a good next step." } : { title: "Keep your study momentum", text: "Your flashcard mastery is progressing. Use AI Tutor to test your understanding from processed PDFs." };
  const maxActivity = Math.max(...weeklyMaterials.map((day) => day.count), 1);

  return <section className="mx-auto max-w-7xl space-y-6 pb-10">
    <section className="relative overflow-hidden rounded-2xl border border-[#39ff14]/20 bg-[radial-gradient(circle_at_80%_20%,rgba(57,255,20,.18),transparent_25%),#0d1110] p-7 shadow-[0_0_35px_rgba(57,255,20,.05)] sm:p-9"><div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#39ff14]/10 blur-3xl" /><div className="relative max-w-2xl"><p className="text-sm text-zinc-400">Good to see you,</p><h1 className="mt-1 text-3xl font-bold text-[#65ff45] sm:text-4xl">{user?.name || "Learner"} <span className="text-white">👋</span></h1><p className="mt-4 max-w-xl text-sm leading-7 text-zinc-300">Your AI study workspace is ready to help you prepare smarter for your semester examinations.</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/upload" className="inline-flex items-center gap-2 rounded-xl bg-[#39ff14] px-4 py-3 text-sm font-bold text-[#071006]"><Sparkles size={17} />Generate Study Material</Link><Link to="/library" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm font-semibold text-zinc-200 hover:border-[#39ff14]/40 hover:text-[#65ff45]"><Plus size={17} />Upload Material</Link></div></div></section>

    {error && <div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-200"><span>{error}</span><button type="button" onClick={() => window.location.reload()} className="rounded-lg border border-red-300/30 px-3 py-2 text-xs">Retry</button></div>}

    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Today&apos;s progress</p><h2 className="mt-2 text-xl font-semibold text-white">Learning progress</h2></div><Target className="text-[#65ff45]" size={22} /></div>{loading ? <div className="mt-6 flex items-center gap-6"><Skeleton className="h-32 w-32 rounded-full" /><Skeleton className="h-20 flex-1" /></div> : <div className="mt-6 flex flex-col items-center gap-6 sm:flex-row"><div className="grid h-36 w-36 shrink-0 place-items-center rounded-full p-3" style={{ background: `conic-gradient(#39ff14 ${progress}%, rgba(57,255,20,.12) 0)` }}><div className="grid h-full w-full place-items-center rounded-full bg-[#0d1110] text-center"><span className="text-3xl font-bold text-[#65ff45]">{progress}%</span><span className="text-[11px] text-zinc-500">mastered</span></div></div><div><p className="text-sm text-zinc-300">{analytics?.learnedCards || 0} of {analytics?.flashcards || 0} flashcards marked learned.</p><p className="mt-3 text-sm text-zinc-500">Study hours and daily streaks will appear when study-session tracking is available.</p><div className="mt-4 flex items-center gap-2 text-xs text-zinc-500"><Flame size={15} className="text-orange-300" />Streak not tracked yet</div></div></div>}</section><section className="rounded-2xl border border-[#39ff14]/20 bg-[#39ff14]/[.04] p-6"><div className="flex items-center gap-2 text-[#65ff45]"><Sparkles size={19} /><p className="text-xs font-semibold uppercase tracking-[.2em]">Genie AI</p></div><h2 className="mt-4 text-xl font-semibold text-white">What would you like to study today?</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Ask questions grounded in your processed study materials.</p><Link to="/chatbot" className="mt-5 flex items-center justify-between rounded-xl border border-[#39ff14]/25 bg-black/20 px-4 py-3 text-sm text-zinc-300 hover:border-[#39ff14]/60 hover:text-[#65ff45]">Ask Genie anything… <ArrowRight size={17} /></Link><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white/[.04] px-3 py-1.5 text-[11px] text-zinc-400">Explain a concept</span><span className="rounded-full bg-white/[.04] px-3 py-1.5 text-[11px] text-zinc-400">Create questions</span></div></section></div>

    <section><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Quick actions</p><h2 className="mt-2 text-xl font-semibold text-white">Start a focused session</h2></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ActionCard icon={Sparkles} title="Generate Notes" description="Create exam-ready study material" to="/upload" /><ActionCard icon={UploadCloud} title="Upload Material" description="Add a PDF to your library" to="/library" accent="muted" /><ActionCard icon={BrainCircuit} title="Practice" description="Test your knowledge with a quiz" to="/quiz" accent="muted" /><ActionCard icon={MessageCircle} title="Ask Genie" description="Study with your AI Tutor" to="/chatbot" accent="muted" /></div></section>

    {loading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <Skeleton key={item} />)}</div> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={FileText} label="Materials" value={analytics?.pdfs || 0} /><StatCard icon={BookOpen} label="Notes Generated" value={analytics?.notes || 0} /><StatCard icon={Trophy} label="Quizzes Created" value={analytics?.quizzes || 0} hint="Question practice history is not stored yet" /><StatCard icon={Clock3} label="Study Hours" value="—" hint="Study sessions are not tracked yet" /></div>}

    <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Continue studying</p><h2 className="mt-2 text-xl font-semibold text-white">Recent materials</h2></div><Link to="/library" className="text-xs text-[#65ff45] hover:underline">View library →</Link></div>{loading ? <div className="mt-5 space-y-3"><Skeleton className="h-16" /><Skeleton className="h-16" /></div> : recentPdfs.length ? <div className="mt-4 divide-y divide-white/[.07]">{recentPdfs.map((pdf) => <div key={pdf._id} className="flex items-center gap-3 py-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-400/10 text-red-300"><FileText size={18} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-zinc-200">{pdf.title}</p><p className="mt-1 text-xs text-zinc-500">{pdf.totalPages || 0} pages · Updated {dateLabel(pdf.updatedAt || pdf.createdAt)}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] ${pdf.status === "completed" ? "bg-[#39ff14]/10 text-[#65ff45]" : "bg-amber-300/10 text-amber-100"}`}>{pdf.status === "completed" ? "Ready" : pdf.status}</span></div>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-zinc-500">Upload your first study material to begin.</div>}</section><section className="rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Weekly activity</p><h2 className="mt-2 text-xl font-semibold text-white">Materials studied</h2></div><Link to="/analytics" className="text-xs text-[#65ff45] hover:underline">Analytics →</Link></div><div className="mt-8 flex h-44 items-end gap-2 sm:gap-4">{weeklyMaterials.map((day) => <div key={day.date.toISOString()} className="flex flex-1 flex-col items-center gap-2"><span className="text-[10px] text-zinc-500">{day.count || ""}</span><div className="flex h-28 w-full items-end rounded-t-lg bg-white/[.03]"><div className="w-full rounded-t-lg bg-gradient-to-t from-[#168a0c] to-[#65ff45] transition-all duration-700" style={{ height: `${day.count ? Math.max(12, (day.count / maxActivity) * 100) : 4}%` }} /></div><span className="text-[10px] text-zinc-500">{day.label}</span></div>)}</div><p className="mt-3 text-xs text-zinc-600">Based on materials and notes created in the last seven days. Study hours are not recorded yet.</p></section></div>

    <div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><section className="rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Upcoming</p><h2 className="mt-2 text-xl font-semibold text-white">Study planner</h2></div><CalendarDays className="text-[#65ff45]" size={21} /></div><div className="mt-5 rounded-xl border border-dashed border-white/10 p-5 text-sm leading-6 text-zinc-500">Planner tasks are not available yet. Add your study schedule when planner tracking is enabled.</div><Link to="/planner" className="mt-4 inline-flex items-center gap-2 text-sm text-[#65ff45]">View Planner <ArrowRight size={15} /></Link></section><section className="rounded-2xl border border-[#39ff14]/20 bg-[#39ff14]/[.04] p-6"><div className="flex items-center gap-2 text-[#65ff45]"><Target size={19} /><p className="text-xs font-semibold uppercase tracking-[.2em]">Exam preparation</p></div><h2 className="mt-3 text-xl font-semibold text-white">Semester Examination</h2><p className="mt-2 text-sm text-zinc-400">Overall preparation based on flashcard mastery</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#39ff14] transition-all duration-700" style={{ width: `${progress}%` }} /></div><div className="mt-2 flex justify-between text-xs text-zinc-500"><span>{progress}% recorded mastery</span><span>{analytics?.flashcards || 0} flashcards</span></div><p className="mt-5 text-xs text-zinc-500">Strong and weak subject areas will appear once subject-tagged study activity is available.</p></section></div>

    <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Recent generations</p><h2 className="mt-2 text-xl font-semibold text-white">Your latest resources</h2></div><Link to="/notes" className="text-xs text-[#65ff45] hover:underline">View notes →</Link></div>{recentNotes.length ? <div className="mt-4 divide-y divide-white/[.07]">{recentNotes.map((note) => <div key={note._id} className="flex items-center gap-3 py-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#39ff14]/10 text-[#65ff45]"><Layers3 size={18} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-zinc-200">{note.title}</p><p className="mt-1 text-xs text-zinc-500">Generated {dateLabel(note.createdAt)}</p></div><Link to="/notes" className="text-xs text-[#65ff45]">Open</Link></div>)}</div> : <p className="mt-5 rounded-xl border border-dashed border-white/10 p-5 text-sm text-zinc-500">Generated resources will appear here after you create notes.</p>}</section><section className="rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-center gap-2 text-[#65ff45]"><BrainCircuit size={19} /><p className="text-xs font-semibold uppercase tracking-[.2em]">Genie recommends</p></div><h2 className="mt-3 text-xl font-semibold text-white">{recommendation.title}</h2><p className="mt-2 text-sm leading-6 text-zinc-400">{recommendation.text}</p><Link to={!pdfs.length ? "/library" : "/chatbot"} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#39ff14] px-4 py-2.5 text-sm font-bold text-[#071006]">Start revision <ArrowRight size={16} /></Link><div className="mt-6 flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.025] p-3 text-xs text-zinc-500"><CheckCircle2 size={16} className="text-[#65ff45]" />Recommendation uses recorded workspace activity</div></section></div>
  </section>;
}
