import { useEffect, useState } from "react";
import { Layers3, RotateCcw, Sparkles } from "lucide-react";
import api from "../api/axios";

export default function Flashcards() {
  const [pdfs, setPdfs] = useState([]); const [selected, setSelected] = useState(""); const [cards, setCards] = useState([]); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(""); const [flipped, setFlipped] = useState({});
  useEffect(() => { api.get("/pdf").then(({ data }) => { setPdfs(data); if (data[0]) setSelected(data[0]._id); }).catch(e => setError(e.response?.data?.message || "Could not load materials.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selected) { setCards([]); return; } api.get(`/flashcards/${selected}`).then(({ data }) => setCards(data.flashcards)).catch(e => setError(e.response?.data?.message || "Could not load flashcards.")); }, [selected]);
  const generate = async () => { setWorking(true); setError(""); try { const { data } = await api.post("/flashcards/generate", { pdfId: selected, regenerate: true }); setCards(data.flashcards); } catch (e) { setError(e.response?.data?.message || "Could not generate flashcards."); } finally { setWorking(false); } };
  const updateCard = async (card) => { try { const { data } = await api.put(`/flashcards/${card._id}`, { isLearned: !card.isLearned }); setCards(all => all.map(item => item._id === card._id ? data.flashcard : item)); } catch (e) { setError(e.response?.data?.message || "Could not update card."); } };
  const mastered = cards.filter(card => card.isLearned).length;
  return <section className="mx-auto max-w-7xl space-y-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#65ff45]">Active recall</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-bold"><Layers3 className="text-[#65ff45]"/>Flashcards</h1><p className="mt-2 text-sm text-zinc-400">Generate a real deck from your processed study material.</p></div><div className="neon-card rounded-xl px-4 py-3 text-sm text-zinc-300"><b className="text-[#65ff45]">{mastered}/{cards.length}</b> cards mastered</div></header>{error && <p role="alert" className="rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-red-200">{error}</p>}<article className="neon-card flex flex-col gap-3 rounded-[18px] p-4 sm:flex-row"><select value={selected} onChange={e => setSelected(e.target.value)} disabled={loading} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-sm"><option value="">Choose processed material</option>{pdfs.map(pdf => <option key={pdf._id} value={pdf._id} disabled={pdf.status !== "completed"}>{pdf.title} — {pdf.status}</option>)}</select><button onClick={generate} disabled={!selected || working} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#39ff14] px-5 py-3 text-sm font-bold text-[#071006] disabled:bg-zinc-700 disabled:text-zinc-500"><Sparkles size={17}/>{working ? "Generating…" : "Generate deck"}</button></article>{!loading && selected && !cards.length ? <div className="neon-card rounded-[18px] p-10 text-center text-zinc-500">No cards in this deck yet. Generate flashcards to begin reviewing.</div> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map((card, index) => <article key={card._id} className="neon-card group min-h-[230px] rounded-[18px] p-5 transition duration-300 hover:-translate-y-1 hover:border-[#39ff14]/35"><div className="flex items-center justify-between"><span className="rounded-full bg-[#39ff14]/10 px-2.5 py-1 text-xs font-medium text-[#65ff45]">{card.isLearned ? "Mastered" : `Card ${index + 1}`}</span><span className="text-xs text-zinc-600">{card.difficulty}</span></div><p className="mt-7 text-xs uppercase tracking-[.16em] text-zinc-500">{flipped[card._id] ? "Answer" : "Question"}</p><h2 className="mt-3 text-lg font-semibold leading-7 text-white">{flipped[card._id] ? card.answer : card.question}</h2><div className="mt-7 flex gap-2"><button onClick={() => setFlipped(state => ({ ...state, [card._id]: !state[card._id] }))} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm text-zinc-300 hover:border-[#39ff14]/40"><RotateCcw size={15}/>Flip</button><button onClick={() => updateCard(card)} className="rounded-lg bg-white/[.06] px-3 py-2 text-sm text-zinc-300 hover:text-[#65ff45]">{card.isLearned ? "Review again" : "Mark learned"}</button></div></article>)}</div>}</section>;
}
