import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Flame, Plus, RefreshCw, Sparkles, Target, Trash2, X } from "lucide-react";
import { Link } from "react-router-dom";
import api from "../api/axios";

const today = new Date();
const isoDate = (date) => date.toISOString().slice(0, 10);
const dateText = (date) => new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric" });
const emptyForm = { title: "", subject: "General", date: isoDate(today), startTime: "09:00", duration: 45, priority: "medium" };

function Status({ status }) { return <span className={`rounded-full px-2.5 py-1 text-[11px] ${status === "completed" ? "bg-[#39ff14]/10 text-[#65ff45]" : status === "in_progress" ? "bg-sky-400/10 text-sky-200" : status === "missed" || status === "skipped" ? "bg-red-400/10 text-red-200" : "bg-amber-300/10 text-amber-100"}`}>{String(status || "not_started").replaceAll("_", " ")}</span>; }

function Task({ task, onStatus, onDelete, onStart }) {
  return <article className="rounded-2xl border border-white/10 bg-[#0d1110] p-4 transition hover:border-[#39ff14]/30"><div className="flex items-start gap-3"><button type="button" onClick={() => onStatus(task, task.status === "completed" ? "not_started" : "completed")} className={`mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-md border ${task.status === "completed" ? "border-[#39ff14] bg-[#39ff14] text-[#071006]" : "border-white/20 text-transparent hover:border-[#39ff14]"}`} aria-label={task.status === "completed" ? "Mark task incomplete" : "Mark task complete"}><Check size={14} /></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className={`font-medium ${task.status === "completed" ? "text-zinc-500 line-through" : "text-white"}`}>{task.title}</h3><Status status={task.status} /></div><p className="mt-1 text-xs text-zinc-500">{task.subject}{task.topic ? ` · ${task.topic}` : ""}</p><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-zinc-500"><span className="inline-flex items-center gap-1"><Clock3 size={13} />{task.startTime} · {task.duration} min</span><span className={task.priority === "high" ? "text-red-200" : "text-zinc-500"}>{task.priority} priority</span></div></div><button type="button" onClick={() => onDelete(task)} className="rounded-lg p-1.5 text-zinc-600 hover:bg-red-500/10 hover:text-red-300" aria-label={`Delete ${task.title}`}><Trash2 size={15} /></button></div>{task.status !== "completed" && <button type="button" onClick={() => onStart(task)} className="mt-4 rounded-lg border border-[#39ff14]/25 px-3 py-2 text-xs font-semibold text-[#65ff45] hover:bg-[#39ff14]/10">Start focus session</button>}</article>;
}

function TaskModal({ onClose, onSave, initial = emptyForm }) {
  const [form, setForm] = useState(initial);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><form onSubmit={(event) => { event.preventDefault(); onSave(form); }} className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold text-white">Add study task</h2><p className="mt-1 text-sm text-zinc-500">Plan a focused, realistic learning block.</p></div><button type="button" onClick={onClose} className="text-zinc-400" aria-label="Close"><X size={19} /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-xs text-zinc-500">Task title</span><input required value={form.title} onChange={(event) => update("title", event.target.value)} placeholder="Study normalization" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none focus:border-[#39ff14]/50" /></label><label><span className="text-xs text-zinc-500">Subject</span><input value={form.subject} onChange={(event) => update("subject", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label><label><span className="text-xs text-zinc-500">Date</span><input type="date" value={form.date} onChange={(event) => update("date", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label><label><span className="text-xs text-zinc-500">Start time</span><input type="time" value={form.startTime} onChange={(event) => update("startTime", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label><label><span className="text-xs text-zinc-500">Duration (minutes)</span><input type="number" min="5" max="720" value={form.duration} onChange={(event) => update("duration", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label><label><span className="text-xs text-zinc-500">Priority</span><select value={form.priority} onChange={(event) => update("priority", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#101311] p-3 text-sm text-white outline-none"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><button className="mt-6 w-full rounded-xl bg-[#39ff14] px-4 py-3 text-sm font-bold text-[#071006]">Save task</button></form></div>;
}

function PlanModal({ onClose, onGenerate }) {
  const [form, setForm] = useState({ goal: "Prepare for semester examination", availableDays: 14, dailyStudyTime: 4, subjects: "Data Structures, DBMS, Operating Systems, Computer Networks", priority: "balanced", startDate: isoDate(today) });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><form onSubmit={(event) => { event.preventDefault(); onGenerate({ ...form, subjects: form.subjects.split(",").map((subject) => subject.trim()).filter(Boolean) }); }} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-start justify-between"><div><h2 className="flex items-center gap-2 text-xl font-semibold text-white"><Sparkles className="text-[#65ff45]" size={20} />Generate study plan</h2><p className="mt-1 text-sm text-zinc-500">Build a structured plan from your goal, available time, subjects, and processed materials.</p></div><button type="button" onClick={onClose} className="text-zinc-400" aria-label="Close"><X size={19} /></button></div><div className="mt-5 space-y-4"><label><span className="text-xs text-zinc-500">Goal</span><input value={form.goal} onChange={(event) => update("goal", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label><label><span className="text-xs text-zinc-500">Subjects (comma separated)</span><input value={form.subjects} onChange={(event) => update("subjects", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label><div className="grid gap-4 sm:grid-cols-3"><label><span className="text-xs text-zinc-500">Available days</span><input type="number" min="1" max="90" value={form.availableDays} onChange={(event) => update("availableDays", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label><label><span className="text-xs text-zinc-500">Hours / day</span><input type="number" min=".25" max="16" step=".25" value={form.dailyStudyTime} onChange={(event) => update("dailyStudyTime", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label><label><span className="text-xs text-zinc-500">Start date</span><input type="date" value={form.startDate} onChange={(event) => update("startDate", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm text-white outline-none" /></label></div><label><span className="text-xs text-zinc-500">Priority strategy</span><select value={form.priority} onChange={(event) => update("priority", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#101311] p-3 text-sm text-white outline-none"><option value="balanced">Balanced</option><option value="weak">Weak subjects first</option></select></label></div><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#39ff14] px-4 py-3 text-sm font-bold text-[#071006]"><Sparkles size={17} />Generate My Study Plan</button></form></div>;
}

export default function Planner() {
  const [tasks, setTasks] = useState([]); const [analytics, setAnalytics] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [view, setView] = useState("day"); const [date, setDate] = useState(isoDate(today)); const [taskModal, setTaskModal] = useState(false); const [planModal, setPlanModal] = useState(false); const [timer, setTimer] = useState(null);
  const load = async () => { setLoading(true); setError(""); try { const [taskResponse, analyticsResponse] = await Promise.all([api.get("/planner"), api.get("/planner/analytics")]); setTasks(taskResponse.data.tasks || []); setAnalytics(analyticsResponse.data.analytics); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to load your study plan."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!timer) return undefined; const interval = setInterval(() => setTimer((current) => current && current.remaining > 0 ? { ...current, remaining: current.remaining - 1 } : null), 1000); return () => clearInterval(interval); }, [timer]);
  const visibleTasks = useMemo(() => { if (view === "day") return tasks.filter((task) => String(task.date).slice(0, 10) === date); const start = new Date(`${date}T12:00:00`); const end = new Date(start); end.setDate(end.getDate() + (view === "week" ? 7 : 30)); return tasks.filter((task) => new Date(task.date) >= start && new Date(task.date) < end); }, [date, tasks, view]);
  const todayTasks = tasks.filter((task) => String(task.date).slice(0, 10) === isoDate(today)); const completedToday = todayTasks.filter((task) => task.status === "completed").length; const nextTask = todayTasks.find((task) => task.status !== "completed") || tasks.find((task) => task.status !== "completed");
  const saveTask = async (form) => { try { const { data } = await api.post("/planner/tasks", form); setTasks((items) => [...items, data.task]); setTaskModal(false); } catch (requestError) { setError(requestError.response?.data?.message || "Could not create task."); } };
  const generate = async (form) => { try { const { data } = await api.post("/planner/generate", form); setTasks(data.tasks || []); setPlanModal(false); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Could not generate study plan."); } };
  const status = async (task, nextStatus) => { try { const { data } = await api.put(`/planner/tasks/${task._id}`, { status: nextStatus, actualDuration: nextStatus === "completed" ? task.duration : undefined }); setTasks((items) => items.map((item) => item._id === task._id ? data.task : item)); setAnalytics((current) => current); } catch (requestError) { setError(requestError.response?.data?.message || "Could not update task."); } };
  const remove = async (task) => { if (!window.confirm("Delete this planner task?")) return; try { await api.delete(`/planner/tasks/${task._id}`); setTasks((items) => items.filter((item) => item._id !== task._id)); } catch (requestError) { setError(requestError.response?.data?.message || "Could not delete task."); } };
  const start = (task) => setTimer({ task, remaining: Number(task.duration || 45) * 60 });
  const minutes = timer ? `${String(Math.floor(timer.remaining / 60)).padStart(2, "0")}:${String(timer.remaining % 60).padStart(2, "0")}` : "";

  return <section className="mx-auto max-w-7xl space-y-6 pb-10"><header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#65ff45]">AI learning workspace</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-bold text-white"><CalendarDays className="text-[#65ff45]" />STUDY PLANNER</h1><p className="mt-2 text-sm text-zinc-400">Your AI-powered path to consistent learning.</p></div><div className="flex flex-wrap gap-3"><button type="button" onClick={() => setPlanModal(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#39ff14] px-4 py-3 text-sm font-bold text-[#071006]"><Sparkles size={17} />Generate AI Plan</button><button type="button" onClick={() => setTaskModal(true)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm font-semibold text-zinc-200 hover:border-[#39ff14]/40 hover:text-[#65ff45]"><Plus size={17} />Add Task</button></div></header>
    {error && <div role="alert" className="flex items-center justify-between gap-3 rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-200"><span>{error}</span><button type="button" onClick={load} className="inline-flex items-center gap-2 rounded-lg border border-red-300/30 px-3 py-2 text-xs"><RefreshCw size={14} />Retry</button></div>}
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-[#39ff14]/25 bg-[radial-gradient(circle_at_90%_10%,rgba(57,255,20,.16),transparent_32%),#0d1110] p-6"><div className="flex items-center gap-2 text-[#65ff45]"><Sparkles size={18} /><p className="text-xs font-semibold uppercase tracking-[.2em]">Study now</p></div><h2 className="mt-4 text-2xl font-semibold text-white">{nextTask ? nextTask.title : "What should I study now?"}</h2><p className="mt-2 text-sm text-zinc-400">{nextTask ? `${nextTask.subject} · ${nextTask.duration} minutes · ${nextTask.priority} priority` : "Generate a plan or add your first focused task."}</p>{nextTask ? <button type="button" onClick={() => start(nextTask)} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#39ff14] px-4 py-3 text-sm font-bold text-[#071006]">Start Focus Session <ArrowRight size={16} /></button> : <button type="button" onClick={() => setPlanModal(true)} className="mt-6 rounded-xl bg-[#39ff14] px-4 py-3 text-sm font-bold text-[#071006]">Generate My Plan</button>}</section><section className="rounded-2xl border border-white/10 bg-[#0d1110] p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Today&apos;s progress</p><div className="mt-4 flex items-end justify-between"><div><p className="text-4xl font-bold text-white">{completedToday}<span className="text-xl text-zinc-500">/{todayTasks.length}</span></p><p className="mt-1 text-sm text-zinc-400">tasks completed</p></div><div className="text-right"><p className="text-2xl font-semibold text-[#65ff45]">{analytics?.completionRate || 0}%</p><p className="text-xs text-zinc-500">overall completion</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#39ff14] transition-all duration-700" style={{ width: `${todayTasks.length ? (completedToday / todayTasks.length) * 100 : 0}%` }} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs text-zinc-500"><span className="inline-flex items-center gap-1"><Clock3 size={13} />{analytics?.plannedHours || 0}h planned</span><span className="inline-flex items-center gap-1"><Target size={13} />{analytics?.actualHours || 0}h actual</span><span className="inline-flex items-center gap-1"><Flame size={13} />{analytics?.streak ?? "—"} streak</span></div></section></div>
    <section className="rounded-2xl border border-white/10 bg-[#0d1110] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><button type="button" onClick={() => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() - (view === "week" ? 7 : 1)); setDate(isoDate(next)); }} className="rounded-lg border border-white/10 p-2 text-zinc-400 hover:text-white" aria-label="Previous period"><ChevronLeft size={17} /></button><button type="button" onClick={() => setDate(isoDate(today))} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-zinc-300">Today</button><button type="button" onClick={() => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + (view === "week" ? 7 : 1)); setDate(isoDate(next)); }} className="rounded-lg border border-white/10 p-2 text-zinc-400 hover:text-white" aria-label="Next period"><ChevronRight size={17} /></button><span className="text-sm text-zinc-400">{dateText(date)}</span></div><div className="flex rounded-xl border border-white/10 p-1">{["day", "week", "month"].map((item) => <button type="button" key={item} onClick={() => setView(item)} className={`rounded-lg px-3 py-2 text-xs capitalize ${view === item ? "bg-[#39ff14] font-semibold text-[#071006]" : "text-zinc-400"}`}>{item}</button>)}</div></div>{loading ? <div className="mt-5 h-36 animate-pulse rounded-xl bg-white/[.04]" /> : visibleTasks.length ? <div className="mt-5 grid gap-3">{visibleTasks.map((task) => <Task key={task._id} task={task} onStatus={status} onDelete={remove} onStart={start} />)}</div> : <div className="mt-5 rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-zinc-500">No tasks scheduled for this view. Add a task or generate a plan.</div>}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-[#0d1110] p-6"><div className="flex items-center gap-2 text-[#65ff45]"><Target size={19} /><p className="text-xs font-semibold uppercase tracking-[.2em]">Planner analytics</p></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-2xl font-semibold text-white">{analytics?.totalTasks || 0}</p><p className="text-xs text-zinc-500">Total tasks</p></div><div><p className="text-2xl font-semibold text-white">{analytics?.completionRate || 0}%</p><p className="text-xs text-zinc-500">Completion</p></div><div><p className="text-2xl font-semibold text-white">{analytics?.plannedHours || 0}h</p><p className="text-xs text-zinc-500">Planned</p></div><div><p className="text-2xl font-semibold text-white">{analytics?.averageSessionMinutes || 0}m</p><p className="text-xs text-zinc-500">Avg session</p></div></div><p className="mt-5 text-xs leading-5 text-zinc-600">Analytics use recorded planner tasks. Quiz accuracy, streaks, and external activity will appear after their tracking models are available.</p></section><section className="rounded-2xl border border-[#39ff14]/20 bg-[#39ff14]/[.04] p-6"><div className="flex items-center gap-2 text-[#65ff45]"><Flame size={19} /><p className="text-xs font-semibold uppercase tracking-[.2em]">Genie adjustment</p></div><h2 className="mt-3 text-lg font-semibold text-white">Keep your plan realistic</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Completed tasks are preserved. Generate a new plan only when your goals or available study time changes.</p><Link to="/chatbot" className="mt-5 inline-flex items-center gap-2 text-sm text-[#65ff45]">Ask AI Tutor for help <ArrowRight size={15} /></Link></section></div>
    {timer && <div className="fixed bottom-5 right-5 z-40 w-[min(360px,calc(100vw-2rem))] rounded-2xl border border-[#39ff14]/40 bg-[#101713] p-5 shadow-[0_0_35px_rgba(57,255,20,.18)]"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#65ff45]">Focus session</p><h2 className="mt-2 font-semibold text-white">{timer.task.title}</h2></div><button type="button" onClick={() => setTimer(null)} className="text-zinc-500" aria-label="Close timer"><X size={17} /></button></div><p className="mt-5 text-center text-4xl font-bold text-[#65ff45]">{minutes}</p><button type="button" onClick={async () => { await status(timer.task, "completed"); setTimer(null); }} className="mt-5 w-full rounded-xl bg-[#39ff14] px-4 py-3 text-sm font-bold text-[#071006]">Finish Session</button></div>}
    {taskModal && <TaskModal onClose={() => setTaskModal(false)} onSave={saveTask} />}{planModal && <PlanModal onClose={() => setPlanModal(false)} onGenerate={generate} />}
  </section>;
}
